version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
#    ports:
#      - "15432:5432"
    volumes:
      - "postgresql-data:/var/lib/postgresql/data"
    networks:
      - test-network

  users_app:
    depends_on:
      - db
    image: users:0.0.1-SNAPSHOT
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=mydb
    ports:
      - "8800:8080"
    networks:
      - test-network

volumes:
  postgresql-data:

networks:
  test-network:
    driver: bridge
